start:
	go run main.go
update-pkg:
	go get -u github.com/nhatlang19/go-monorepo/pkg@23409def8d3a504ee3b66fab49358a46d04d702e && \
	go get -u github.com/nhatlang19/go-monorepo/services/mail@23409def8d3a504ee3b66fab49358a46d04d702e