start:
	go run main.go
update-pkg-head:
	go get -u github.com/nhatlang19/go-monorepo/pkg@HEAD && \
	go get -u github.com/nhatlang19/go-monorepo/services/mail@HEAD
update-pkg:
	go get -u github.com/nhatlang19/go-monorepo/pkg && \
	go get -u github.com/nhatlang19/go-monorepo/services/mail