start:
	go run main.go
update-pkg:
	go get -u github.com/nhatlang19/go-monorepo/pkg@18ec415ae2db7dd99b9f3b4d51f26866f65a2657 && \
	go get -u github.com/nhatlang19/go-monorepo/services/mail@18ec415ae2db7dd99b9f3b4d51f26866f65a2657