// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: mailpb/mail.proto

package mailpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *RegisterMailRequest) Reset() {
	*x = RegisterMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mailpb_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMailRequest) ProtoMessage() {}

func (x *RegisterMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mailpb_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMailRequest.ProtoReflect.Descriptor instead.
func (*RegisterMailRequest) Descriptor() ([]byte, []int) {
	return file_mailpb_mail_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMailRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type RegisterMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RegisterMailResponse) Reset() {
	*x = RegisterMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mailpb_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMailResponse) ProtoMessage() {}

func (x *RegisterMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mailpb_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMailResponse.ProtoReflect.Descriptor instead.
func (*RegisterMailResponse) Descriptor() ([]byte, []int) {
	return file_mailpb_mail_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMailResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_mailpb_mail_proto protoreflect.FileDescriptor

var file_mailpb_mail_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x61, 0x69, 0x6c, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x27, 0x0a, 0x13, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a,
	0x77, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0x5a, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4b, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3f,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x68, 0x61,
	0x74, 0x6c, 0x61, 0x6e, 0x67, 0x31, 0x39, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x6f, 0x6e, 0x6f, 0x72,
	0x65, 0x70, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x69,
	0x6c, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x70, 0x62, 0x3b, 0x6d, 0x61, 0x69, 0x6c, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mailpb_mail_proto_rawDescOnce sync.Once
	file_mailpb_mail_proto_rawDescData = file_mailpb_mail_proto_rawDesc
)

func file_mailpb_mail_proto_rawDescGZIP() []byte {
	file_mailpb_mail_proto_rawDescOnce.Do(func() {
		file_mailpb_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_mailpb_mail_proto_rawDescData)
	})
	return file_mailpb_mail_proto_rawDescData
}

var file_mailpb_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mailpb_mail_proto_goTypes = []interface{}{
	(*RegisterMailRequest)(nil),  // 0: mail.RegisterMailRequest
	(*RegisterMailResponse)(nil), // 1: mail.RegisterMailResponse
}
var file_mailpb_mail_proto_depIdxs = []int32{
	0, // 0: mail.MailService.SendRegisterMail:input_type -> mail.RegisterMailRequest
	1, // 1: mail.MailService.SendRegisterMail:output_type -> mail.RegisterMailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mailpb_mail_proto_init() }
func file_mailpb_mail_proto_init() {
	if File_mailpb_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mailpb_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mailpb_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mailpb_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailpb_mail_proto_goTypes,
		DependencyIndexes: file_mailpb_mail_proto_depIdxs,
		MessageInfos:      file_mailpb_mail_proto_msgTypes,
	}.Build()
	File_mailpb_mail_proto = out.File
	file_mailpb_mail_proto_rawDesc = nil
	file_mailpb_mail_proto_goTypes = nil
	file_mailpb_mail_proto_depIdxs = nil
}
